namespace EventBus.Infrastructure.Models
{
    public enum FailureCode
    {
        Unknown,
        Unauthorized,
        NotFound,
        ValidationError,
        InvalidOperation,
        DuplicateId,
        DuplicateEmail,
        DbError,
        DbConcurrency,
        Timeout,
        InternalServerError,
        ConfigExists,
        CreateConfigFailed,
        GetConfigFailed,
        UpdateConfigFailed,
        DeleteConfigFailed,
        GetAllConfigsFailed,
        EnqueueError,
        DequeueError,
        TryDequeueError,
        PeekError,
        ClearError,
        ClearQueueError,
        ScheduledTaskQueryFailed,
        ScheduledTaskUpdateFailed
    }
}
